[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I"]
ignore = []
exclude = ["data", ".env", "*.sqlite3", "*.pkl"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=app --cov-report=xml"
testpaths = [
    "tests"
]