services:
  - type: web
    name: guardianx-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8080
    envVars:
      - key: DATA_DIR
        value: /app/data
      - key: DATABASE_URL
        value: sqlite:///app/data/guardianx.sqlite3
      - key: MODEL_PATH
        value: /app/data/model.pkl